import type { GroupId } from "../types";

// 2026 FIFA World Cup full match schedule — all 104 matches (72 group + 32
// knockout). Group results are filled in as matches are played; knockout slots
// (e.g. "1A", "2B", "W73", "3ABCDF") resolve to teams once earlier rounds
// finish. See labelSlot() in components/Schedule.tsx for human-readable slots.
//
// Generated by scripts/update-schedule.mjs from the open-source 26worldcup
// dataset (github.com/26worldcup/26worldcup.github.io, public/data), which
// mirrors FIFA's official schedule and results. Do not edit by hand.
// Snapshot updatedAt: 2026-06-18T21:15:51.324Z

export type Stage = "group" | "r32" | "r16" | "qf" | "sf" | "third" | "final";

export interface MatchSide {
  /** Team id (matches Team.id) once known, else null for an unresolved slot. */
  code: string | null;
  score: number | null;
  /** Penalty-shootout score, or null if not applicable. */
  pen: number | null;
}

export interface Match {
  /** Official match number, 1-104. */
  n: number;
  stage: Stage;
  group: GroupId | null;
  /** Kick-off, ISO 8601 UTC. */
  date: string;
  venue: string;
  status: "finished" | "scheduled" | string;
  home: MatchSide;
  away: MatchSide;
  /** Bracket slot token for the home side, e.g. "A1", "1A", "W73". */
  phA: string | null;
  phB: string | null;
  /** Winning team id once decided, else null. */
  winner: string | null;
}

export const SCHEDULE_UPDATED_AT = "2026-06-18T21:15:51.324Z";

export const MATCHES: Match[] = [
  {
    "n": 1,
    "stage": "group",
    "group": "A",
    "date": "2026-06-11T19:00:00Z",
    "venue": "Estadio Azteca (Estadio Banorte) · Mexico City",
    "status": "finished",
    "home": {
      "code": "MEX",
      "score": 2,
      "pen": null
    },
    "away": {
      "code": "RSA",
      "score": 0,
      "pen": null
    },
    "phA": "A1",
    "phB": "A2",
    "winner": "MEX"
  },
  {
    "n": 2,
    "stage": "group",
    "group": "A",
    "date": "2026-06-12T02:00:00Z",
    "venue": "Estadio Akron · Zapopan (Guadalajara)",
    "status": "finished",
    "home": {
      "code": "KOR",
      "score": 2,
      "pen": null
    },
    "away": {
      "code": "CZE",
      "score": 1,
      "pen": null
    },
    "phA": "A3",
    "phB": "A4",
    "winner": "KOR"
  },
  {
    "n": 3,
    "stage": "group",
    "group": "B",
    "date": "2026-06-12T19:00:00Z",
    "venue": "BMO Field · Toronto",
    "status": "finished",
    "home": {
      "code": "CAN",
      "score": 1,
      "pen": null
    },
    "away": {
      "code": "BIH",
      "score": 1,
      "pen": null
    },
    "phA": "B1",
    "phB": "B2",
    "winner": null
  },
  {
    "n": 4,
    "stage": "group",
    "group": "D",
    "date": "2026-06-13T01:00:00Z",
    "venue": "SoFi Stadium · Inglewood (Los Angeles)",
    "status": "finished",
    "home": {
      "code": "USA",
      "score": 4,
      "pen": null
    },
    "away": {
      "code": "PAR",
      "score": 1,
      "pen": null
    },
    "phA": "D1",
    "phB": "D2",
    "winner": "USA"
  },
  {
    "n": 5,
    "stage": "group",
    "group": "C",
    "date": "2026-06-14T01:00:00Z",
    "venue": "Gillette Stadium · Foxborough (Boston)",
    "status": "finished",
    "home": {
      "code": "HAI",
      "score": 0,
      "pen": null
    },
    "away": {
      "code": "SCO",
      "score": 1,
      "pen": null
    },
    "phA": "C3",
    "phB": "C4",
    "winner": "SCO"
  },
  {
    "n": 6,
    "stage": "group",
    "group": "D",
    "date": "2026-06-14T04:00:00Z",
    "venue": "BC Place · Vancouver",
    "status": "finished",
    "home": {
      "code": "AUS",
      "score": 2,
      "pen": null
    },
    "away": {
      "code": "TUR",
      "score": 0,
      "pen": null
    },
    "phA": "D3",
    "phB": "D4",
    "winner": "AUS"
  },
  {
    "n": 7,
    "stage": "group",
    "group": "C",
    "date": "2026-06-13T22:00:00Z",
    "venue": "MetLife Stadium · East Rutherford (New York/New Jersey)",
    "status": "finished",
    "home": {
      "code": "BRA",
      "score": 1,
      "pen": null
    },
    "away": {
      "code": "MAR",
      "score": 1,
      "pen": null
    },
    "phA": "C1",
    "phB": "C2",
    "winner": null
  },
  {
    "n": 8,
    "stage": "group",
    "group": "B",
    "date": "2026-06-13T19:00:00Z",
    "venue": "Levi's Stadium · Santa Clara (SF Bay Area)",
    "status": "finished",
    "home": {
      "code": "QAT",
      "score": 1,
      "pen": null
    },
    "away": {
      "code": "SUI",
      "score": 1,
      "pen": null
    },
    "phA": "B3",
    "phB": "B4",
    "winner": null
  },
  {
    "n": 9,
    "stage": "group",
    "group": "E",
    "date": "2026-06-14T23:00:00Z",
    "venue": "Lincoln Financial Field · Philadelphia",
    "status": "finished",
    "home": {
      "code": "CIV",
      "score": 1,
      "pen": null
    },
    "away": {
      "code": "ECU",
      "score": 0,
      "pen": null
    },
    "phA": "E3",
    "phB": "E4",
    "winner": "CIV"
  },
  {
    "n": 10,
    "stage": "group",
    "group": "E",
    "date": "2026-06-14T17:00:00Z",
    "venue": "NRG Stadium · Houston",
    "status": "finished",
    "home": {
      "code": "GER",
      "score": 7,
      "pen": null
    },
    "away": {
      "code": "CUW",
      "score": 1,
      "pen": null
    },
    "phA": "E1",
    "phB": "E2",
    "winner": "GER"
  },
  {
    "n": 11,
    "stage": "group",
    "group": "F",
    "date": "2026-06-14T20:00:00Z",
    "venue": "AT&T Stadium · Arlington (Dallas)",
    "status": "finished",
    "home": {
      "code": "NED",
      "score": 2,
      "pen": null
    },
    "away": {
      "code": "JPN",
      "score": 2,
      "pen": null
    },
    "phA": "F1",
    "phB": "F2",
    "winner": null
  },
  {
    "n": 12,
    "stage": "group",
    "group": "F",
    "date": "2026-06-15T02:00:00Z",
    "venue": "Estadio BBVA · Guadalupe (Monterrey)",
    "status": "finished",
    "home": {
      "code": "SWE",
      "score": 5,
      "pen": null
    },
    "away": {
      "code": "TUN",
      "score": 1,
      "pen": null
    },
    "phA": "F3",
    "phB": "F4",
    "winner": "SWE"
  },
  {
    "n": 13,
    "stage": "group",
    "group": "H",
    "date": "2026-06-15T22:00:00Z",
    "venue": "Hard Rock Stadium · Miami Gardens",
    "status": "finished",
    "home": {
      "code": "KSA",
      "score": 1,
      "pen": null
    },
    "away": {
      "code": "URU",
      "score": 1,
      "pen": null
    },
    "phA": "H3",
    "phB": "H4",
    "winner": null
  },
  {
    "n": 14,
    "stage": "group",
    "group": "H",
    "date": "2026-06-15T16:00:00Z",
    "venue": "Mercedes-Benz Stadium · Atlanta",
    "status": "finished",
    "home": {
      "code": "ESP",
      "score": 0,
      "pen": null
    },
    "away": {
      "code": "CPV",
      "score": 0,
      "pen": null
    },
    "phA": "H1",
    "phB": "H2",
    "winner": null
  },
  {
    "n": 15,
    "stage": "group",
    "group": "G",
    "date": "2026-06-16T01:00:00Z",
    "venue": "SoFi Stadium · Inglewood (Los Angeles)",
    "status": "finished",
    "home": {
      "code": "IRN",
      "score": 2,
      "pen": null
    },
    "away": {
      "code": "NZL",
      "score": 2,
      "pen": null
    },
    "phA": "G3",
    "phB": "G4",
    "winner": null
  },
  {
    "n": 16,
    "stage": "group",
    "group": "G",
    "date": "2026-06-15T19:00:00Z",
    "venue": "Lumen Field · Seattle",
    "status": "finished",
    "home": {
      "code": "BEL",
      "score": 1,
      "pen": null
    },
    "away": {
      "code": "EGY",
      "score": 1,
      "pen": null
    },
    "phA": "G1",
    "phB": "G2",
    "winner": null
  },
  {
    "n": 17,
    "stage": "group",
    "group": "I",
    "date": "2026-06-16T19:00:00Z",
    "venue": "MetLife Stadium · East Rutherford (New York/New Jersey)",
    "status": "finished",
    "home": {
      "code": "FRA",
      "score": 3,
      "pen": null
    },
    "away": {
      "code": "SEN",
      "score": 1,
      "pen": null
    },
    "phA": "I1",
    "phB": "I2",
    "winner": "FRA"
  },
  {
    "n": 18,
    "stage": "group",
    "group": "I",
    "date": "2026-06-16T22:00:00Z",
    "venue": "Gillette Stadium · Foxborough (Boston)",
    "status": "finished",
    "home": {
      "code": "IRQ",
      "score": 1,
      "pen": null
    },
    "away": {
      "code": "NOR",
      "score": 4,
      "pen": null
    },
    "phA": "I3",
    "phB": "I4",
    "winner": "NOR"
  },
  {
    "n": 19,
    "stage": "group",
    "group": "J",
    "date": "2026-06-17T01:00:00Z",
    "venue": "Arrowhead Stadium (GEHA Field) · Kansas City",
    "status": "finished",
    "home": {
      "code": "ARG",
      "score": 3,
      "pen": null
    },
    "away": {
      "code": "ALG",
      "score": 0,
      "pen": null
    },
    "phA": "J1",
    "phB": "J2",
    "winner": "ARG"
  },
  {
    "n": 20,
    "stage": "group",
    "group": "J",
    "date": "2026-06-17T04:00:00Z",
    "venue": "Levi's Stadium · Santa Clara (SF Bay Area)",
    "status": "finished",
    "home": {
      "code": "AUT",
      "score": 3,
      "pen": null
    },
    "away": {
      "code": "JOR",
      "score": 1,
      "pen": null
    },
    "phA": "J3",
    "phB": "J4",
    "winner": "AUT"
  },
  {
    "n": 21,
    "stage": "group",
    "group": "L",
    "date": "2026-06-17T23:00:00Z",
    "venue": "BMO Field · Toronto",
    "status": "finished",
    "home": {
      "code": "GHA",
      "score": 1,
      "pen": null
    },
    "away": {
      "code": "PAN",
      "score": 0,
      "pen": null
    },
    "phA": "L3",
    "phB": "L4",
    "winner": "GHA"
  },
  {
    "n": 22,
    "stage": "group",
    "group": "L",
    "date": "2026-06-17T20:00:00Z",
    "venue": "AT&T Stadium · Arlington (Dallas)",
    "status": "finished",
    "home": {
      "code": "ENG",
      "score": 4,
      "pen": null
    },
    "away": {
      "code": "CRO",
      "score": 2,
      "pen": null
    },
    "phA": "L1",
    "phB": "L2",
    "winner": "ENG"
  },
  {
    "n": 23,
    "stage": "group",
    "group": "K",
    "date": "2026-06-17T17:00:00Z",
    "venue": "NRG Stadium · Houston",
    "status": "finished",
    "home": {
      "code": "POR",
      "score": 1,
      "pen": null
    },
    "away": {
      "code": "COD",
      "score": 1,
      "pen": null
    },
    "phA": "K1",
    "phB": "K2",
    "winner": null
  },
  {
    "n": 24,
    "stage": "group",
    "group": "K",
    "date": "2026-06-18T02:00:00Z",
    "venue": "Estadio Azteca (Estadio Banorte) · Mexico City",
    "status": "finished",
    "home": {
      "code": "UZB",
      "score": 1,
      "pen": null
    },
    "away": {
      "code": "COL",
      "score": 3,
      "pen": null
    },
    "phA": "K3",
    "phB": "K4",
    "winner": "COL"
  },
  {
    "n": 25,
    "stage": "group",
    "group": "A",
    "date": "2026-06-18T16:00:00Z",
    "venue": "Mercedes-Benz Stadium · Atlanta",
    "status": "finished",
    "home": {
      "code": "CZE",
      "score": 1,
      "pen": null
    },
    "away": {
      "code": "RSA",
      "score": 1,
      "pen": null
    },
    "phA": "A4",
    "phB": "A2",
    "winner": null
  },
  {
    "n": 26,
    "stage": "group",
    "group": "B",
    "date": "2026-06-18T19:00:00Z",
    "venue": "SoFi Stadium · Inglewood (Los Angeles)",
    "status": "finished",
    "home": {
      "code": "SUI",
      "score": 4,
      "pen": null
    },
    "away": {
      "code": "BIH",
      "score": 1,
      "pen": null
    },
    "phA": "B4",
    "phB": "B2",
    "winner": "SUI"
  },
  {
    "n": 27,
    "stage": "group",
    "group": "B",
    "date": "2026-06-18T22:00:00Z",
    "venue": "BC Place · Vancouver",
    "status": "scheduled",
    "home": {
      "code": "CAN",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "QAT",
      "score": null,
      "pen": null
    },
    "phA": "B1",
    "phB": "B3",
    "winner": null
  },
  {
    "n": 28,
    "stage": "group",
    "group": "A",
    "date": "2026-06-19T01:00:00Z",
    "venue": "Estadio Akron · Zapopan (Guadalajara)",
    "status": "scheduled",
    "home": {
      "code": "MEX",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "KOR",
      "score": null,
      "pen": null
    },
    "phA": "A1",
    "phB": "A3",
    "winner": null
  },
  {
    "n": 29,
    "stage": "group",
    "group": "C",
    "date": "2026-06-20T00:30:00Z",
    "venue": "Lincoln Financial Field · Philadelphia",
    "status": "scheduled",
    "home": {
      "code": "BRA",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "HAI",
      "score": null,
      "pen": null
    },
    "phA": "C1",
    "phB": "C3",
    "winner": null
  },
  {
    "n": 30,
    "stage": "group",
    "group": "C",
    "date": "2026-06-19T22:00:00Z",
    "venue": "Gillette Stadium · Foxborough (Boston)",
    "status": "scheduled",
    "home": {
      "code": "SCO",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "MAR",
      "score": null,
      "pen": null
    },
    "phA": "C4",
    "phB": "C2",
    "winner": null
  },
  {
    "n": 31,
    "stage": "group",
    "group": "D",
    "date": "2026-06-20T03:00:00Z",
    "venue": "Levi's Stadium · Santa Clara (SF Bay Area)",
    "status": "scheduled",
    "home": {
      "code": "TUR",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "PAR",
      "score": null,
      "pen": null
    },
    "phA": "D4",
    "phB": "D2",
    "winner": null
  },
  {
    "n": 32,
    "stage": "group",
    "group": "D",
    "date": "2026-06-19T19:00:00Z",
    "venue": "Lumen Field · Seattle",
    "status": "scheduled",
    "home": {
      "code": "USA",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "AUS",
      "score": null,
      "pen": null
    },
    "phA": "D1",
    "phB": "D3",
    "winner": null
  },
  {
    "n": 33,
    "stage": "group",
    "group": "E",
    "date": "2026-06-20T20:00:00Z",
    "venue": "BMO Field · Toronto",
    "status": "scheduled",
    "home": {
      "code": "GER",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "CIV",
      "score": null,
      "pen": null
    },
    "phA": "E1",
    "phB": "E3",
    "winner": null
  },
  {
    "n": 34,
    "stage": "group",
    "group": "E",
    "date": "2026-06-21T00:00:00Z",
    "venue": "Arrowhead Stadium (GEHA Field) · Kansas City",
    "status": "scheduled",
    "home": {
      "code": "ECU",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "CUW",
      "score": null,
      "pen": null
    },
    "phA": "E4",
    "phB": "E2",
    "winner": null
  },
  {
    "n": 35,
    "stage": "group",
    "group": "F",
    "date": "2026-06-20T17:00:00Z",
    "venue": "NRG Stadium · Houston",
    "status": "scheduled",
    "home": {
      "code": "NED",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "SWE",
      "score": null,
      "pen": null
    },
    "phA": "F1",
    "phB": "F3",
    "winner": null
  },
  {
    "n": 36,
    "stage": "group",
    "group": "F",
    "date": "2026-06-21T04:00:00Z",
    "venue": "Estadio BBVA · Guadalupe (Monterrey)",
    "status": "scheduled",
    "home": {
      "code": "TUN",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "JPN",
      "score": null,
      "pen": null
    },
    "phA": "F4",
    "phB": "F2",
    "winner": null
  },
  {
    "n": 37,
    "stage": "group",
    "group": "H",
    "date": "2026-06-21T22:00:00Z",
    "venue": "Hard Rock Stadium · Miami Gardens",
    "status": "scheduled",
    "home": {
      "code": "URU",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "CPV",
      "score": null,
      "pen": null
    },
    "phA": "H4",
    "phB": "H2",
    "winner": null
  },
  {
    "n": 38,
    "stage": "group",
    "group": "H",
    "date": "2026-06-21T16:00:00Z",
    "venue": "Mercedes-Benz Stadium · Atlanta",
    "status": "scheduled",
    "home": {
      "code": "ESP",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "KSA",
      "score": null,
      "pen": null
    },
    "phA": "H1",
    "phB": "H3",
    "winner": null
  },
  {
    "n": 39,
    "stage": "group",
    "group": "G",
    "date": "2026-06-21T19:00:00Z",
    "venue": "SoFi Stadium · Inglewood (Los Angeles)",
    "status": "scheduled",
    "home": {
      "code": "BEL",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "IRN",
      "score": null,
      "pen": null
    },
    "phA": "G1",
    "phB": "G3",
    "winner": null
  },
  {
    "n": 40,
    "stage": "group",
    "group": "G",
    "date": "2026-06-22T01:00:00Z",
    "venue": "BC Place · Vancouver",
    "status": "scheduled",
    "home": {
      "code": "NZL",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "EGY",
      "score": null,
      "pen": null
    },
    "phA": "G4",
    "phB": "G2",
    "winner": null
  },
  {
    "n": 41,
    "stage": "group",
    "group": "I",
    "date": "2026-06-23T00:00:00Z",
    "venue": "MetLife Stadium · East Rutherford (New York/New Jersey)",
    "status": "scheduled",
    "home": {
      "code": "NOR",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "SEN",
      "score": null,
      "pen": null
    },
    "phA": "I4",
    "phB": "I2",
    "winner": null
  },
  {
    "n": 42,
    "stage": "group",
    "group": "I",
    "date": "2026-06-22T21:00:00Z",
    "venue": "Lincoln Financial Field · Philadelphia",
    "status": "scheduled",
    "home": {
      "code": "FRA",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "IRQ",
      "score": null,
      "pen": null
    },
    "phA": "I1",
    "phB": "I3",
    "winner": null
  },
  {
    "n": 43,
    "stage": "group",
    "group": "J",
    "date": "2026-06-22T17:00:00Z",
    "venue": "AT&T Stadium · Arlington (Dallas)",
    "status": "scheduled",
    "home": {
      "code": "ARG",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "AUT",
      "score": null,
      "pen": null
    },
    "phA": "J1",
    "phB": "J3",
    "winner": null
  },
  {
    "n": 44,
    "stage": "group",
    "group": "J",
    "date": "2026-06-23T03:00:00Z",
    "venue": "Levi's Stadium · Santa Clara (SF Bay Area)",
    "status": "scheduled",
    "home": {
      "code": "JOR",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "ALG",
      "score": null,
      "pen": null
    },
    "phA": "J4",
    "phB": "J2",
    "winner": null
  },
  {
    "n": 45,
    "stage": "group",
    "group": "L",
    "date": "2026-06-23T20:00:00Z",
    "venue": "Gillette Stadium · Foxborough (Boston)",
    "status": "scheduled",
    "home": {
      "code": "ENG",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "GHA",
      "score": null,
      "pen": null
    },
    "phA": "L1",
    "phB": "L3",
    "winner": null
  },
  {
    "n": 46,
    "stage": "group",
    "group": "L",
    "date": "2026-06-23T23:00:00Z",
    "venue": "BMO Field · Toronto",
    "status": "scheduled",
    "home": {
      "code": "PAN",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "CRO",
      "score": null,
      "pen": null
    },
    "phA": "L4",
    "phB": "L2",
    "winner": null
  },
  {
    "n": 47,
    "stage": "group",
    "group": "K",
    "date": "2026-06-23T17:00:00Z",
    "venue": "NRG Stadium · Houston",
    "status": "scheduled",
    "home": {
      "code": "POR",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "UZB",
      "score": null,
      "pen": null
    },
    "phA": "K1",
    "phB": "K3",
    "winner": null
  },
  {
    "n": 48,
    "stage": "group",
    "group": "K",
    "date": "2026-06-24T02:00:00Z",
    "venue": "Estadio Akron · Zapopan (Guadalajara)",
    "status": "scheduled",
    "home": {
      "code": "COL",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "COD",
      "score": null,
      "pen": null
    },
    "phA": "K4",
    "phB": "K2",
    "winner": null
  },
  {
    "n": 49,
    "stage": "group",
    "group": "C",
    "date": "2026-06-24T22:00:00Z",
    "venue": "Hard Rock Stadium · Miami Gardens",
    "status": "scheduled",
    "home": {
      "code": "SCO",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "BRA",
      "score": null,
      "pen": null
    },
    "phA": "C4",
    "phB": "C1",
    "winner": null
  },
  {
    "n": 50,
    "stage": "group",
    "group": "C",
    "date": "2026-06-24T22:00:00Z",
    "venue": "Mercedes-Benz Stadium · Atlanta",
    "status": "scheduled",
    "home": {
      "code": "MAR",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "HAI",
      "score": null,
      "pen": null
    },
    "phA": "C2",
    "phB": "C3",
    "winner": null
  },
  {
    "n": 51,
    "stage": "group",
    "group": "B",
    "date": "2026-06-24T19:00:00Z",
    "venue": "BC Place · Vancouver",
    "status": "scheduled",
    "home": {
      "code": "SUI",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "CAN",
      "score": null,
      "pen": null
    },
    "phA": "B4",
    "phB": "B1",
    "winner": null
  },
  {
    "n": 52,
    "stage": "group",
    "group": "B",
    "date": "2026-06-24T19:00:00Z",
    "venue": "Lumen Field · Seattle",
    "status": "scheduled",
    "home": {
      "code": "BIH",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "QAT",
      "score": null,
      "pen": null
    },
    "phA": "B2",
    "phB": "B3",
    "winner": null
  },
  {
    "n": 53,
    "stage": "group",
    "group": "A",
    "date": "2026-06-25T01:00:00Z",
    "venue": "Estadio Azteca (Estadio Banorte) · Mexico City",
    "status": "scheduled",
    "home": {
      "code": "CZE",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "MEX",
      "score": null,
      "pen": null
    },
    "phA": "A4",
    "phB": "A1",
    "winner": null
  },
  {
    "n": 54,
    "stage": "group",
    "group": "A",
    "date": "2026-06-25T01:00:00Z",
    "venue": "Estadio BBVA · Guadalupe (Monterrey)",
    "status": "scheduled",
    "home": {
      "code": "RSA",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "KOR",
      "score": null,
      "pen": null
    },
    "phA": "A2",
    "phB": "A3",
    "winner": null
  },
  {
    "n": 55,
    "stage": "group",
    "group": "E",
    "date": "2026-06-25T20:00:00Z",
    "venue": "Lincoln Financial Field · Philadelphia",
    "status": "scheduled",
    "home": {
      "code": "CUW",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "CIV",
      "score": null,
      "pen": null
    },
    "phA": "E2",
    "phB": "E3",
    "winner": null
  },
  {
    "n": 56,
    "stage": "group",
    "group": "E",
    "date": "2026-06-25T20:00:00Z",
    "venue": "MetLife Stadium · East Rutherford (New York/New Jersey)",
    "status": "scheduled",
    "home": {
      "code": "ECU",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "GER",
      "score": null,
      "pen": null
    },
    "phA": "E4",
    "phB": "E1",
    "winner": null
  },
  {
    "n": 57,
    "stage": "group",
    "group": "F",
    "date": "2026-06-25T23:00:00Z",
    "venue": "AT&T Stadium · Arlington (Dallas)",
    "status": "scheduled",
    "home": {
      "code": "JPN",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "SWE",
      "score": null,
      "pen": null
    },
    "phA": "F2",
    "phB": "F3",
    "winner": null
  },
  {
    "n": 58,
    "stage": "group",
    "group": "F",
    "date": "2026-06-25T23:00:00Z",
    "venue": "Arrowhead Stadium (GEHA Field) · Kansas City",
    "status": "scheduled",
    "home": {
      "code": "TUN",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "NED",
      "score": null,
      "pen": null
    },
    "phA": "F4",
    "phB": "F1",
    "winner": null
  },
  {
    "n": 59,
    "stage": "group",
    "group": "D",
    "date": "2026-06-26T02:00:00Z",
    "venue": "SoFi Stadium · Inglewood (Los Angeles)",
    "status": "scheduled",
    "home": {
      "code": "TUR",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "USA",
      "score": null,
      "pen": null
    },
    "phA": "D4",
    "phB": "D1",
    "winner": null
  },
  {
    "n": 60,
    "stage": "group",
    "group": "D",
    "date": "2026-06-26T02:00:00Z",
    "venue": "Levi's Stadium · Santa Clara (SF Bay Area)",
    "status": "scheduled",
    "home": {
      "code": "PAR",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "AUS",
      "score": null,
      "pen": null
    },
    "phA": "D2",
    "phB": "D3",
    "winner": null
  },
  {
    "n": 61,
    "stage": "group",
    "group": "I",
    "date": "2026-06-26T19:00:00Z",
    "venue": "Gillette Stadium · Foxborough (Boston)",
    "status": "scheduled",
    "home": {
      "code": "NOR",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "FRA",
      "score": null,
      "pen": null
    },
    "phA": "I4",
    "phB": "I1",
    "winner": null
  },
  {
    "n": 62,
    "stage": "group",
    "group": "I",
    "date": "2026-06-26T19:00:00Z",
    "venue": "BMO Field · Toronto",
    "status": "scheduled",
    "home": {
      "code": "SEN",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "IRQ",
      "score": null,
      "pen": null
    },
    "phA": "I2",
    "phB": "I3",
    "winner": null
  },
  {
    "n": 63,
    "stage": "group",
    "group": "G",
    "date": "2026-06-27T03:00:00Z",
    "venue": "Lumen Field · Seattle",
    "status": "scheduled",
    "home": {
      "code": "EGY",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "IRN",
      "score": null,
      "pen": null
    },
    "phA": "G2",
    "phB": "G3",
    "winner": null
  },
  {
    "n": 64,
    "stage": "group",
    "group": "G",
    "date": "2026-06-27T03:00:00Z",
    "venue": "BC Place · Vancouver",
    "status": "scheduled",
    "home": {
      "code": "NZL",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "BEL",
      "score": null,
      "pen": null
    },
    "phA": "G4",
    "phB": "G1",
    "winner": null
  },
  {
    "n": 65,
    "stage": "group",
    "group": "H",
    "date": "2026-06-27T00:00:00Z",
    "venue": "NRG Stadium · Houston",
    "status": "scheduled",
    "home": {
      "code": "CPV",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "KSA",
      "score": null,
      "pen": null
    },
    "phA": "H2",
    "phB": "H3",
    "winner": null
  },
  {
    "n": 66,
    "stage": "group",
    "group": "H",
    "date": "2026-06-27T00:00:00Z",
    "venue": "Estadio Akron · Zapopan (Guadalajara)",
    "status": "scheduled",
    "home": {
      "code": "URU",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "ESP",
      "score": null,
      "pen": null
    },
    "phA": "H4",
    "phB": "H1",
    "winner": null
  },
  {
    "n": 67,
    "stage": "group",
    "group": "L",
    "date": "2026-06-27T21:00:00Z",
    "venue": "MetLife Stadium · East Rutherford (New York/New Jersey)",
    "status": "scheduled",
    "home": {
      "code": "PAN",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "ENG",
      "score": null,
      "pen": null
    },
    "phA": "L4",
    "phB": "L1",
    "winner": null
  },
  {
    "n": 68,
    "stage": "group",
    "group": "L",
    "date": "2026-06-27T21:00:00Z",
    "venue": "Lincoln Financial Field · Philadelphia",
    "status": "scheduled",
    "home": {
      "code": "CRO",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "GHA",
      "score": null,
      "pen": null
    },
    "phA": "L2",
    "phB": "L3",
    "winner": null
  },
  {
    "n": 69,
    "stage": "group",
    "group": "J",
    "date": "2026-06-28T02:00:00Z",
    "venue": "Arrowhead Stadium (GEHA Field) · Kansas City",
    "status": "scheduled",
    "home": {
      "code": "ALG",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "AUT",
      "score": null,
      "pen": null
    },
    "phA": "J2",
    "phB": "J3",
    "winner": null
  },
  {
    "n": 70,
    "stage": "group",
    "group": "J",
    "date": "2026-06-28T02:00:00Z",
    "venue": "AT&T Stadium · Arlington (Dallas)",
    "status": "scheduled",
    "home": {
      "code": "JOR",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "ARG",
      "score": null,
      "pen": null
    },
    "phA": "J4",
    "phB": "J1",
    "winner": null
  },
  {
    "n": 71,
    "stage": "group",
    "group": "K",
    "date": "2026-06-27T23:30:00Z",
    "venue": "Hard Rock Stadium · Miami Gardens",
    "status": "scheduled",
    "home": {
      "code": "COL",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "POR",
      "score": null,
      "pen": null
    },
    "phA": "K4",
    "phB": "K1",
    "winner": null
  },
  {
    "n": 72,
    "stage": "group",
    "group": "K",
    "date": "2026-06-27T23:30:00Z",
    "venue": "Mercedes-Benz Stadium · Atlanta",
    "status": "scheduled",
    "home": {
      "code": "COD",
      "score": null,
      "pen": null
    },
    "away": {
      "code": "UZB",
      "score": null,
      "pen": null
    },
    "phA": "K2",
    "phB": "K3",
    "winner": null
  },
  {
    "n": 73,
    "stage": "r32",
    "group": null,
    "date": "2026-06-28T19:00:00Z",
    "venue": "SoFi Stadium · Inglewood (Los Angeles)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "2A",
    "phB": "2B",
    "winner": null
  },
  {
    "n": 74,
    "stage": "r32",
    "group": null,
    "date": "2026-06-29T20:30:00Z",
    "venue": "Gillette Stadium · Foxborough (Boston)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "1E",
    "phB": "3ABCDF",
    "winner": null
  },
  {
    "n": 75,
    "stage": "r32",
    "group": null,
    "date": "2026-06-30T01:00:00Z",
    "venue": "Estadio BBVA · Guadalupe (Monterrey)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "1F",
    "phB": "2C",
    "winner": null
  },
  {
    "n": 76,
    "stage": "r32",
    "group": null,
    "date": "2026-06-29T17:00:00Z",
    "venue": "NRG Stadium · Houston",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "1C",
    "phB": "2F",
    "winner": null
  },
  {
    "n": 77,
    "stage": "r32",
    "group": null,
    "date": "2026-06-30T21:00:00Z",
    "venue": "MetLife Stadium · East Rutherford (New York/New Jersey)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "1I",
    "phB": "3CDFGH",
    "winner": null
  },
  {
    "n": 78,
    "stage": "r32",
    "group": null,
    "date": "2026-06-30T17:00:00Z",
    "venue": "AT&T Stadium · Arlington (Dallas)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "2E",
    "phB": "2I",
    "winner": null
  },
  {
    "n": 79,
    "stage": "r32",
    "group": null,
    "date": "2026-07-01T01:00:00Z",
    "venue": "Estadio Azteca (Estadio Banorte) · Mexico City",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "1A",
    "phB": "3CEFHI",
    "winner": null
  },
  {
    "n": 80,
    "stage": "r32",
    "group": null,
    "date": "2026-07-01T16:00:00Z",
    "venue": "Mercedes-Benz Stadium · Atlanta",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "1L",
    "phB": "3EHIJK",
    "winner": null
  },
  {
    "n": 81,
    "stage": "r32",
    "group": null,
    "date": "2026-07-02T00:00:00Z",
    "venue": "Levi's Stadium · Santa Clara (SF Bay Area)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "1D",
    "phB": "3BEFIJ",
    "winner": null
  },
  {
    "n": 82,
    "stage": "r32",
    "group": null,
    "date": "2026-07-01T20:00:00Z",
    "venue": "Lumen Field · Seattle",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "1G",
    "phB": "3AEHIJ",
    "winner": null
  },
  {
    "n": 83,
    "stage": "r32",
    "group": null,
    "date": "2026-07-02T23:00:00Z",
    "venue": "BMO Field · Toronto",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "2K",
    "phB": "2L",
    "winner": null
  },
  {
    "n": 84,
    "stage": "r32",
    "group": null,
    "date": "2026-07-02T19:00:00Z",
    "venue": "SoFi Stadium · Inglewood (Los Angeles)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "1H",
    "phB": "2J",
    "winner": null
  },
  {
    "n": 85,
    "stage": "r32",
    "group": null,
    "date": "2026-07-03T03:00:00Z",
    "venue": "BC Place · Vancouver",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "1B",
    "phB": "3EFGIJ",
    "winner": null
  },
  {
    "n": 86,
    "stage": "r32",
    "group": null,
    "date": "2026-07-03T22:00:00Z",
    "venue": "Hard Rock Stadium · Miami Gardens",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "1J",
    "phB": "2H",
    "winner": null
  },
  {
    "n": 87,
    "stage": "r32",
    "group": null,
    "date": "2026-07-04T01:30:00Z",
    "venue": "Arrowhead Stadium (GEHA Field) · Kansas City",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "1K",
    "phB": "3DEIJL",
    "winner": null
  },
  {
    "n": 88,
    "stage": "r32",
    "group": null,
    "date": "2026-07-03T18:00:00Z",
    "venue": "AT&T Stadium · Arlington (Dallas)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "2D",
    "phB": "2G",
    "winner": null
  },
  {
    "n": 89,
    "stage": "r16",
    "group": null,
    "date": "2026-07-04T21:00:00Z",
    "venue": "Lincoln Financial Field · Philadelphia",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W74",
    "phB": "W77",
    "winner": null
  },
  {
    "n": 90,
    "stage": "r16",
    "group": null,
    "date": "2026-07-04T17:00:00Z",
    "venue": "NRG Stadium · Houston",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W73",
    "phB": "W75",
    "winner": null
  },
  {
    "n": 91,
    "stage": "r16",
    "group": null,
    "date": "2026-07-05T20:00:00Z",
    "venue": "MetLife Stadium · East Rutherford (New York/New Jersey)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W76",
    "phB": "W78",
    "winner": null
  },
  {
    "n": 92,
    "stage": "r16",
    "group": null,
    "date": "2026-07-06T00:00:00Z",
    "venue": "Estadio Azteca (Estadio Banorte) · Mexico City",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W79",
    "phB": "W80",
    "winner": null
  },
  {
    "n": 93,
    "stage": "r16",
    "group": null,
    "date": "2026-07-06T19:00:00Z",
    "venue": "AT&T Stadium · Arlington (Dallas)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W83",
    "phB": "W84",
    "winner": null
  },
  {
    "n": 94,
    "stage": "r16",
    "group": null,
    "date": "2026-07-07T00:00:00Z",
    "venue": "Lumen Field · Seattle",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W81",
    "phB": "W82",
    "winner": null
  },
  {
    "n": 95,
    "stage": "r16",
    "group": null,
    "date": "2026-07-07T16:00:00Z",
    "venue": "Mercedes-Benz Stadium · Atlanta",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W86",
    "phB": "W88",
    "winner": null
  },
  {
    "n": 96,
    "stage": "r16",
    "group": null,
    "date": "2026-07-07T20:00:00Z",
    "venue": "BC Place · Vancouver",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W85",
    "phB": "W87",
    "winner": null
  },
  {
    "n": 97,
    "stage": "qf",
    "group": null,
    "date": "2026-07-09T20:00:00Z",
    "venue": "Gillette Stadium · Foxborough (Boston)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W89",
    "phB": "W90",
    "winner": null
  },
  {
    "n": 98,
    "stage": "qf",
    "group": null,
    "date": "2026-07-10T19:00:00Z",
    "venue": "SoFi Stadium · Inglewood (Los Angeles)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W93",
    "phB": "W94",
    "winner": null
  },
  {
    "n": 99,
    "stage": "qf",
    "group": null,
    "date": "2026-07-11T21:00:00Z",
    "venue": "Hard Rock Stadium · Miami Gardens",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W91",
    "phB": "W92",
    "winner": null
  },
  {
    "n": 100,
    "stage": "qf",
    "group": null,
    "date": "2026-07-12T01:00:00Z",
    "venue": "Arrowhead Stadium (GEHA Field) · Kansas City",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W95",
    "phB": "W96",
    "winner": null
  },
  {
    "n": 101,
    "stage": "sf",
    "group": null,
    "date": "2026-07-14T19:00:00Z",
    "venue": "AT&T Stadium · Arlington (Dallas)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W97",
    "phB": "W98",
    "winner": null
  },
  {
    "n": 102,
    "stage": "sf",
    "group": null,
    "date": "2026-07-15T19:00:00Z",
    "venue": "Mercedes-Benz Stadium · Atlanta",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W99",
    "phB": "W100",
    "winner": null
  },
  {
    "n": 103,
    "stage": "third",
    "group": null,
    "date": "2026-07-18T21:00:00Z",
    "venue": "Hard Rock Stadium · Miami Gardens",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "RU101",
    "phB": "RU102",
    "winner": null
  },
  {
    "n": 104,
    "stage": "final",
    "group": null,
    "date": "2026-07-19T19:00:00Z",
    "venue": "MetLife Stadium · East Rutherford (New York/New Jersey)",
    "status": "scheduled",
    "home": {
      "code": null,
      "score": null,
      "pen": null
    },
    "away": {
      "code": null,
      "score": null,
      "pen": null
    },
    "phA": "W101",
    "phB": "W102",
    "winner": null
  }
];
